from selenium.webdriver.common.by import By

class UrbanRoutes_elments_path():
    main_page = (By.CSS_SELECTOR, 'html')
    reservationForm_from = (By.XPATH, '//div[@class="input-container"]/input[@id="from"]')
    reservationForm_to = (By.CSS_SELECTOR, '.input-container #to')
    mode_panel_selection_optimum = (By.XPATH, '//div[@class="workflow-subcontainer"]/div[@class="type-picker shown"]/div[@class="modes-container"]/div[1]')
    mode_panel_selection_flash = (By.XPATH, '//div[@class="workflow-subcontainer"]/div[@class="type-picker shown"]/div[@class="modes-container"]/div[2]')
    mode_panel_selection_personal = (By.XPATH, '//div[@class="workflow-subcontainer"]/div[@class="type-picker shown"]/div[@class="modes-container"]/div[3]')
    panel_taxi_option = (By.XPATH, '//div[@class="types-container"]/div[3]')
    panel_confirmation_button = (By.XPATH, '//div[@class="results-container"]/div[@class="results-text"]/button[@class="button round"]')
    panel_vehicle_comfort_selection = (By.XPATH, '//div[@class="tariff-picker shown"]/div[@class="tariff-cards"]/div[5]')
    panel_number_field=(By.XPATH, '//div[@class="workflow-subcontainer"]/div[@class="tariff-picker shown"]/div[@class="form"]/div[@class="np-button"]')
    card_phone_number_field = (By.CSS_SELECTOR, 'label.label')
    card_phone_number_input_text = (By.CSS_SELECTOR, '#phone')
    card_phone_number_button_confirmation = (By.XPATH, '//div[@class="buttons"]/button[contains(text(),"Siguiente")]')
    card_input_code_confirmation=(By.XPATH, '//div[@class="np-input"]/div[@class="input-container"]/input[@id="code"]')
    card_confirmation_code_button=(By.XPATH, '//div[@class="buttons"]/button[contains(text(),"Confirmar")]')
    page_form_pay_input=(By.XPATH, '//div[@class="pp-button filled"]/div[contains(text(), "Método de pago")]')
    page_add_pay_card = (By.XPATH, '//div[@class="pp-plus-container"]/img[@class="pp-plus"]')
    input_add_card_pay_number_field = (By.CSS_SELECTOR, 'input#number')
    form_pay_card = (By.XPATH, '//form/div[@class="card-wrapper"]/div[@class="card-number"]/div[contains(text(), "Número de tarjeta (no la tuya):")]')
    input_code_card = (By.CSS_SELECTOR, '.card-code-input input#code')
    confirmation_card_info_button = (By.XPATH, '//button[contains(text(), "Agregar")]')
    close_pay_card_window = (By.XPATH, '//div/div[2]/div[2]/div[1]/button')
    input_message_driver_field = (By.XPATH, '//input[@id="comment"]')
    switch_manta_pañuelos = (By.XPATH, '//div[@class="reqs-body"]/div[1]/div[ @class="r-sw-container"]/div[@class="r-sw"]/div[@class="switch"]/span')
    switch_cortina_acustica = (By.XPATH, '//div[@class="reqs-body"]/div[2]/div[ @class="r-sw-container"]/div[@class="r-sw"]/div[@class="switch"]/span')
    get_ice_cream_quantity = (By.XPATH, '//div[@class="r-group-items"]/div[1]/div[@class="r-counter-container"]/div[@class="r-counter"]/div[@class="counter"]/div[3]')
    get_ice_cream_chocolate_quantity = (By.XPATH, '//div[@class="r-group-items"]/div[2]/div[@class="r-counter-container"]/div[@class="r-counter"]/div[@class="counter"]/div[3]')
    get_ice_cream_strawberry_quantity = (By.XPATH, '//div[@class="r-group-items"]/div[3]/div[@class="r-counter-container"]/div[@class="r-counter"]/div[@class="counter"]/div[3]')
    destination_picker_inputs = (By.CSS_SELECTOR, "div.dst-picker-row")
    destination_picker = (By.XPATH, '//div[@class="dst-picker"]')
    modes_options = (By.CSS_SELECTOR, "div.mode")
    transport_card_options = (By.CSS_SELECTOR, "div.tcard")
    phone_number_confirmation_field = (By.XPATH, '//div[@class="form"]/div[@class="np-button filled"]/div[@class="np-text"]')
    card_number_confirmation_field = (By.XPATH, '//div[@class="pp-button filled"]/div[@class="pp-value"]/div[@class="pp-value-text"]')
    get_ice_cream_quantity_value = (By.XPATH, '//div[@class="r-group-items"]/div[1]/div[@class="r-counter-container"]/div[@class="r-counter"]/div[@class="counter"]/div[2]')


